### ISSUE TITLE
Permission error when running web (rotheross/otobo:latest) image in openshift

### ISSUE THREAD

**Issue by rbr101** [RotherOSS/otobo#1706]
When running the image rotheross/otobo:latest with args -web in openshift i get a permission error.
All the other components start just fine in openshift except the web component.

I have running everything fine in kubernetes as i don't enforce the acl/permissions there. But now moving to Redhat openshift i run into this issue.

```
mv: cannot move '/opt/otobo_install/otobo_next/docker_firsttime' to '/opt/otobo_install/otobo_next/docker_firsttime_handled': Permission denied
Error while loading /opt/otobo/bin/psgi-bin/otobo.psgi: No such file or directory at (eval 5) line 4.
```

My deployment config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - args:
            - web
          env:
            - name: OTOBO_DB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: OTOBO_DB_ROOT_PASSWORD
                  name: env
          image: rotheross/otobo:latest
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: 1
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /opt/otobo
              name: otobo-web-claim0
      restartPolicy: Always
      volumes:
        - name: otobo-web-claim0
          persistentVolumeClaim:
            claimName: otobo-web-claim0
```

**Comment by bschmalhofer** [comment]
Hi @rbr101 ,
it's great to see people running OTOBO on Kubernetes and OpenShift. Especially, as running in OTOBO in OpenShift hasn't been tested yet in-house.

First a recap about _/opt/otobo_ and /opt/otobo_install/otobo_next_ . The working dir of OTOBO is _/opt/otobo_ . For several reasons this directory tree is modified while the application is running and the modifications have to persist. Therefore _/opt/otobo_ is a persistent volume. That persistent volume has to be initialised with files and directories at some time and _/opt/otobo_install/otobo_next_, located on the Docker image, is the source tree. There are two valid cases when the directory tree must be copied:

- Initial setup: when OTOBO is started for the first time, when_/opt/otobo_ is still empty
- Update: Overwrite when there is a new version of the OTOBO Docker image

The existence of the file _/opt/otobo_install/otobo_next/docker_firsttime_ is an additional condition that has to be met before the directory tree is copied. The flag file is intended as an additional safety mechanism, so that _/opt/otobo_ is not inadvertently overwritten. The file is moved out of the way after the initial copy. All of that is done in _/opt/otobo_install/entrypoint.sh_.

Under vanilla Docker-compose this is no problem, the permissions are:
```
bes:~/devel/OTOBO/otobo (rel-10_1)$ docker run otobo:local-10.1.x ls -ld /opt/otobo_install/otobo_next 
drwxr-xr-x 1 otobo otobo 4096 Mar 29 12:07 /opt/otobo_install/otobo_next
bes:~/devel/OTOBO/otobo (rel-10_1)$ docker run otobo:local-10.1.x ls -ld /opt/otobo_install/otobo_next/docker_firsttime
-rw-rw---- 1 otobo otobo 0 Mar 29 12:07 /opt/otobo_install/otobo_next/docker_firsttime
```

The reason why this does not work in OpenShift ist not clear to me. Do you happen to know whether OpenShift has additional security checks? Such that an image mustn't be modified at all? 

A quick workaround might be to simply remove the command  `mv $otobo_next/docker_firsttime $otobo_next/docker_firsttime_handled` in _entrypoint.sh_. As said above, checking the existence of that file is only an additional safety measure.

Best regards,
   Bernhard

**Comment by rbr101** [comment]
Hi,

Thanks for your answer, I'm still figuring out what needs to be changed. The thing with OpenShift is that containers are not allowed to run with root privs.

I added ownership of /opt in the docker file:
```
RUN chown -R 1000:0 /opt
RUN chmod -R g+w /opt
USER $OTOBO_USER
```

The first error is gone now, now I only have this one:
```
Error while loading /opt/otobo/bin/psgi-bin/otobo.psgi: No such file or directory at (eval 5) line 4.
```
Somehow the file is missing because of some privilege stuff, will dig into it to figure out where it's failing.


update:

I manually copied the /opt/otobo_install/otobo_next to /opt/otobo
And then copy the file /opt/otobo/Kernel/Config.pm.docker.dist to/opt/otobo/Kernel/Config.pm 

Now the pod is started and the initial webpage otobo/installer.pm is working

I only have to fix it in the docker file somewhere....

**Comment by bschmalhofer** [comment]
Hi @rbr101 ,

this is a bit confusing. The statements 

RUN chown -R 1000:0 /opt
RUN chmod -R g+w /opt
USER $OTOBO_USER

give write permissions for the root group. This makes sense because  https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids says:

> Notice the Container is using the UID from the Namespace. An important detail to notice is that the user in the Container always has GID=0, which is the root group. 

Could it be the case, that OpenShift assigns a random user id and does not honour the user id that has been declared with `USER $OTOBO_USER` in the Dockerfile? This would explain why the container user is not happy with the tailored permissions in _/opt_.

See also: https://stackoverflow.com/questions/69460157/managing-users-in-openshift and https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html .

Best regards,
   Bernhard

**Comment by rbr101** [comment]
Hi,

I'm not an OpenShift expert, but you are right about OpenShift assigning a random userid.
That' why the initial setup was failing. 

Tomorrow I will look if I can fix this part in the Dockerfile.

Cheers,
Roeland

**Comment by bschmalhofer** [comment]
@rbr101,
I noticed something unrelated  in your deployment config. We have changed the labels of the images on Docker hub. This means that
 
`image: rotheross/otobo:latest`

should now be either

`image: rotheross/otobo:latest-10_0`

or

`image: rotheross/otobo:latest-10_1`

**Comment by rbr101** [comment]
Hi bschmalhofer, 

It took some time before i got the admin privs for openshift. I modified the Dockerfile slightly to get it working.
This is what i did:

```
oc create serviceaccount otobo
oc adm policy add-scc-to-user nonroot -z otobo
```
Then add following to the spec:

```
    spec:
      serviceAccountName: otobo
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
```

But now i have the problem that readWriteMany volumes are not supported for vsphere version < 7.0 UP3 (https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-82AC812A-40E3-4563-9329-747634E1AB6E.html)

So i can't create two pods sharing the same volume.

I now have two options:

1. Merge the Daemon and Web functionality (what is the reason tho have these separated?)
2. Create a NFS share and use this for storage

Before i dig into this, i prefer option 1. Is this also in you opinion the best option ?

Thanks
