### ISSUE TITLE
Failed to Connect to Database

### ISSUE THREAD

**Issue by FuckingToasters** [RotherOSS/otobo#3303]
Hello, so i worked on making a Doscker Compose file but for some reason, it's don't seem to be able to connect to the Database:

```yml
version: '3'

services:
  db:
    image: mariadb:latest
    container_name: otobo_db
    environment:
      MYSQL_USER: otobo
      MYSQL_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
    volumes:
      - helpdesk_otobo_mariadb_data:/var/lib/mysql
    networks:
      - revproxy

  elastic:
    image: elasticsearch:8.13.0 # high servity vuluns
    container_name: otobo_elastic
    volumes:
      - helpdesk_otobo_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - revproxy

  redis:
    image: redis:latest
    container_name: otobo_redis
    environment:
      REDIS_USERNAME: otabo
      REDIS_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
    volumes:
      - helpdesk_otobo_redis_data:/data
    networks:
      - revproxy

  web:
    image: rotheross/otobo:latest
    container_name: otobo
    networks:
      - revproxy
    volumes:
      - helpdesk_otobo_opt:/opt/otobo
    entrypoint: ["/bin/bash", "-c", "/opt/otobo_install/entrypoint.sh web"]

networks:
  revproxy:
    external: true

volumes:
  helpdesk_otobo_opt:
  helpdesk_otobo_mariadb_data:
  helpdesk_otobo_elasticsearch_data:
  helpdesk_otobo_redis_data:
```

**Comment by FuckingToasters** [comment]
> Hello, so i worked on making a Doscker Compose file but for some reason, it's don't seem to be able to connect to the Database:
> 
> ```yaml
> version: '3'
> 
> services:
>   db:
>     image: mariadb:latest
>     container_name: otobo_db
>     environment:
>       MYSQL_USER: otobo
>       MYSQL_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
>       MYSQL_ROOT_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
>     volumes:
>       - helpdesk_otobo_mariadb_data:/var/lib/mysql
>     networks:
>       - revproxy
> 
>   elastic:
>     image: elasticsearch:8.13.0 # high servity vuluns
>     container_name: otobo_elastic
>     volumes:
>       - helpdesk_otobo_elasticsearch_data:/usr/share/elasticsearch/data
>     networks:
>       - revproxy
> 
>   redis:
>     image: redis:latest
>     container_name: otobo_redis
>     environment:
>       REDIS_USERNAME: otabo
>       REDIS_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
>     volumes:
>       - helpdesk_otobo_redis_data:/data
>     networks:
>       - revproxy
> 
>   web:
>     image: rotheross/otobo:latest
>     container_name: otobo
>     networks:
>       - revproxy
>     volumes:
>       - helpdesk_otobo_opt:/opt/otobo
>     entrypoint: ["/bin/bash", "-c", "/opt/otobo_install/entrypoint.sh web"]
> 
> networks:
>   revproxy:
>     external: true
> 
> volumes:
>   helpdesk_otobo_opt:
>   helpdesk_otobo_mariadb_data:
>   helpdesk_otobo_elasticsearch_data:
>   helpdesk_otobo_redis_data:
> ```

Same issue happen with following compose file:
```yml
version: '3.8'

services:

  # the database
  db:
    image: mariadb:10.5
    user: mysql:mysql
    cap_drop:
        - ALL
    cap_add:
        - CAP_SYS_CHROOT
    restart: always
    logging:
        driver: "local"
        options:
            max-file: "5"
            max-size: "10m"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD}
    command: --max-allowed-packet=136314880 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-log-file-size=268435456 --query-cache-size=33554432
    healthcheck:
      test: mysqladmin -h db --user=root --password='${OTOBO_DB_ROOT_PASSWORD}' ping
    networks:
      - revproxy

  # a container running a webserver
  otobo:
    image: rotheross/otobo:latest-10_1
    cap_drop:
        - ALL
    depends_on:
      - db
      - elastic
      - redis
    restart: always
    logging:
        driver: "local"
        options:
            max-file: "5"
            max-size: "10m"
    volumes:
      - opt_otobo:/opt/otobo
    command: web
    healthcheck:
      test: curl -s -f http://localhost:5000/robots.txt
    networks:
      - revproxy

  # a container running the OTOBO daemon
  daemon:
    image: rotheross/otobo:latest-10_1
    cap_drop:
        - ALL
    depends_on:
      - otobo
    restart: always
    logging:
        driver: "local"
        options:
            max-file: "5"
            max-size: "10m"
    volumes:
      - opt_otobo:/opt/otobo
    command: daemon
    healthcheck:
      test: ./bin/otobo.Daemon.pl status | grep 'Daemon running'

  # a container running Elasticsearch
  elastic:
    image: rotheross/otobo-elasticsearch:latest-10_1
    cap_drop:
        - ALL
    cap_add:
        - CAP_SYS_CHROOT
        - CAP_SETUID
        - CAP_SETGID
    restart: always
    logging:
        driver: "local"
        options:
            max-file: "5"
            max-size: "10m"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: your_elasticsearch_java_opts_here
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s -f http://localhost:9200/_cat/health

  # a container running Redis
  redis:
    image: redis:6.0-alpine
    user: redis:redis
    cap_drop:
        - ALL
    restart: always
    logging:
        driver: "local"
        options:
            max-file: "5"
            max-size: "10m"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
    networks:
      - revproxy

networks:
  revproxy:
    external: true

# no volumes need to be exposed across services
volumes:
  mariadb_data: {}
  opt_otobo: {}
  elasticsearch_data: {}
  redis_data: {}
```
