### ISSUE TITLE
Key 'Label' does not work in Dynamic Field Set definition

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3805]
In ticket masks, there is the possibility to overwrite the default label of a dynamic field via YAML definition, like so:

```yml
---
- DF: SomeDFName
  Label: SomeLabel
```

I just noticed that this key does not work with the Dynamic Field Set definitions, but did not yet take a closer look.
