### ISSUE TITLE
Validation bug when storing a dynamic field Set with an incorrect Grid configuration

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#4143]
When storing a dynamic field set with an incorrect grid configuration, like so:

```yml
---
- Grid:
    - Columns: 1
    - Rows:
      -
        - DF: FieldName
```

then an Internal Server Error occurs upon storing because the structure is not validated properly.
